name: 'run-notebook'
description: 'Run notebook'
author: 'asegal'
inputs:
  temp_dir:
    description: 'working directory for the runner. Should be runner.temp'
    required: True
  workspace:
    description: 'the github workspace.  Should be github.workspace'
    required: True
  notebooks:
    description: 'Path to notebook with extension that should be executed'
    required: True
  isReport:
    description: 'If True, will hide inputs in notebook'
    default: 'False'
    required: False
  poll:
    description: 'If True, will hide poll for output'
    default: 'False'
    required: False
branding:
  icon: 'book'
  color: 'orange'
runs:
  using: 'node12'
  main: 'lib/main.js'
